### ISSUE TITLE
Android设备上没有安装微信客户端

### ISSUE THREAD

**Issue by TimmySong** [beecloud/beecloud-android#30]
如果Android设备上没有安装微信客户端，这个时候去调用微信支付的接口，会发现BCResult没有任何返回的情况。看了下调试信息，发现是SDK内部捕获到了异常，并且应该是catch掉了，然后二次开发的我们就的不到任何反馈了，感觉这个可以改善一下。（目前我打算自己去判断有没有安装微信客户端）

**Comment by xuanzhui** [comment]
这个在初始化时demo有示例
String initInfo = BCPay.initWechatPay(ShoppingCartActivity.this, "wxf1aa465362b4c8f1");
if (initInfo != null) {
    Toast.makeText(this, "微信初始化失败：" + initInfo, Toast.LENGTH_LONG).show();
}

另外demo中也在调用微信支付前进行了判断
if (BCPay.isWXAppInstalledAndSupported() &&
        BCPay.isWXPaySupported()) {

    BCPay.getInstance(ShoppingCartActivity.this).reqWXPaymentAsync(
            "安卓微信支付测试",               //订单标题
            1,                           //订单金额(分)
            BillUtils.genBillNum(),  //订单流水号
            mapOptional,            //扩展参数(可以null)
            bcCallback);            //支付完成后回调入口

} else {
    Toast.makeText(ShoppingCartActivity.this,
            "您尚未安装微信或者安装的微信版本不支持", Toast.LENGTH_LONG).show();
}

我觉得这个可以提前判断出来的结果，没有必要先去调用支付API，再去查看异步回调的结果

**Comment by xuanzhui** [comment]
这个issue我先close了，还有问题可以reopen

**Comment by TimmySong** [comment]
好的，三克油。
