### ISSUE TITLE
能否建 gradle 远程jar包依赖，不用每次都替换jar包

### ISSUE THREAD

**Issue by vicre** [beecloud/beecloud-android#45]
compile 'cn.beecloud:xxxx'

**Comment by xuanzhui** [comment]
由于我们的项目依赖腾讯支付宝等公司的闭源jar包，在未得到授权的情况下直接发布到公共开源库，可能会有不必要的纠纷；即使只发布我们自己的jar，也达不到一次性引入依赖的目的，所以暂时没有创建gradle远程jar的计划
