### ISSUE TITLE
unsafe implementation of WebViewClient.onReceivedSslError in cn.beecloud.BCWXWapPaymentActivity

### ISSUE THREAD

**Issue by zzhang5** [beecloud/beecloud-android#46]
google play complains an unsafe implementation of `WebViewClient.onReceivedSslError` in `cn.beecloud.BCWXWapPaymentActivity$1`. The actual code is here:
https://github.com/beecloud/beecloud-android/blob/master/sdk/src/main/java/cn/beecloud/BCWXWapPaymentActivity.java#L81

A simple solution is here:
http://stackoverflow.com/questions/36050741/webview-avoid-security-alert-from-google-play-upon-implementation-of-onreceiveds

Any plan to fix this? Thanks!

**Comment by xuanzhui** [comment]
override removed

**Comment by zzhang5** [comment]
Thanks!
