### ISSUE TITLE
Error:Execution failed for task ':demo:validateSigningDebug'. > Keystore file /Users/pg/Downloads/beecloud-android/demo/debug.keystore not found for signing config 'config'.

### ISSUE THREAD

**Issue by wxh2013** [beecloud/beecloud-android#52]
我想安装demo 应用到手机，  结果发生这个错误

![screen shot 2017-05-21 at 9 54 38 pm](https://cloud.githubusercontent.com/assets/7362131/26284530/1ad5c08a-3e70-11e7-8190-67355cf40385.png)

**Comment by xuanzhui** [comment]
已经上传debug.keystore
