### ISSUE TITLE
getDeviceId: The user 10745 does not meet the requirements to access device identifiers.

### ISSUE THREAD

**Issue by langlangsAgo** [beecloud/beecloud-android#60]
java.lang.SecurityException: getDeviceId: The user 10745 does not meet the requirements to access device identifiers.
targetSDK = 29,
现在高版本手机获取不到了，什么时候适配

**Comment by xuanzhui** [comment]
不需要适配，这是支付宝sdk尝试获取device id，获取不到并不会影响支付结果；另外已经更新支付宝sdk到最新版本，目前观察已经没有怎样的报错
